#!/usr/bin/env bash
_help() {
  attach() {
    echo "Start and attach to a service container its output"
    echo "Usage: dev attach <container-name>"
  } 
  build() {
    echo "Build docker images that are defined in the docker compose file."
    echo "Usage: dev build"
  }
  check() {
    echo "Check whether the currently used template is up-to-date."
    echo "Usage: dev check [-v]"
    echo "Options:"
    echo "  -v  Verbose output"
  }
  dc() {
    echo "Execute a Docker Compose command directly, using configured .env* files."
    echo "Usage: dev dc [options...]"
  }
  down() {
    echo "Turn off development environment."
    echo "Usage: dev down [-a] [options...]"
    echo "Options:"
    echo "  -a  Turn off all development environments"
    echo "For more info, see: docker-compose help down"
  }
  exec() {
    echo "Execute a command on a running service container"
    echo "Usage: dev exec <container> <command> [options...]"
    echo "Example: dev exec redis redis-cli flushall"
    echo "For more info, see: docker-compose help exec"
  }
  init() {
    echo "Initialize a project type for development."
    echo "Usage: dev init [-f|--force] <project-type>"
    echo "Available project types: "
    for type in $(find "$(dirname "$(realpath "$0")")/templates/" -mindepth 1 -maxdepth 1 -type d); do echo "- $(basename "$type")"; done
  }
  logs() {
    echo "Display container output logs."
    echo "Usage: dev logs [-f] [service]"
    echo "For more info, see: docker-compose help logs"
  }
  ps() {
    echo "Display status of service containers"
    echo "Usage: dev ps"
    echo "For more info, see: docker-compose help ps"
  }
  pull() {
    echo "Pull latest development environment images."
    echo "Usage: dev pull"
    echo "For more info, see: docker-compose help pull"
  }
  restart() {
    echo "Restart the environment."
    echo "Usage: dev restart"
  }
  run() {
    echo "Run a command on a temporary service container."
    echo "Usage: dev run <service> <command>"
    echo "For more info, see: docker-compose help run"
  }
  self_update() {
    echo "Run self update."
    echo "Usage: dev self_update"
  }
  up() {
    echo "Turn on development environment."
    echo "Usage: dev up [options...]"
    echo "For more info, see: docker-compose help up"
  }
  if [ "$(type -t "${1:-}")" == "function" ]; then
    "${1:-}"
    return 
  else
    echo Error: Option "${1:-}" not found
    return 1
  fi
}

if ! _help "$@"; then
    echo "Usage: dev <option>"
    echo "The following options are available."
    echo
    echo "General management"
    echo "  build:   Build the services of the Docker Compose configuration"
    echo "  down:    Stop the environment"
    echo "  ps:      Display status of service containers"
    echo "  pull:    Pull latest images of service containers"
    echo "  restart: Restart the environment"
    echo "  up:      Start the environment"
    echo
    echo "Service container interaction"
    echo "  attach: Start and attach to a service container its output"
    echo "  exec:   Execute a command on a running service container"
    echo "  logs:   Display container output logs"
    echo "  run:    Run a command on a temporary service container"
    echo
    echo "Tool management"
    echo "  check:       Check if current template is up-to-date"
    echo "  init:        Initialize a project based on a template"
    echo "  self_update: Run self update"
    echo
    echo "Additional options"
    echo "  dc: Execute a Docker Compose command"
    echo "  help: Display information about an option"
fi
