version: "3.4"
networks:
  default:
    external:
      name: gateway
services:
  traefik:
    image: traefik:v2.4
    container_name: traefik
    command:
      # Enable Docker provider
      - "--providers.docker=true"
      # Only expose explicitly defined services
      - "--providers.docker.exposedByDefault=true"
      # Set log level
      - "--log.level=INFO"
    networks:
      - default
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
      - "5000:5000"
      - "8000:8000"
      - "8080:8080"
      - "8443:8443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
